apiVersion: v1
kind: LimitRange
metadata:
  name: default-limits
  namespace: default  # Cambiar esto al namespace donde quieres aplicar las reglas
spec:
  limits:
  - default:
      cpu: "500m"
      memory: "512Mi"
    defaultRequest:
      cpu: "250m"
      memory: "256Mi"
    type: Container
